FROM rockylinux:9

ENV NODE_VERSION v18.18.1
ENV NVM_DIR /root/.nvm

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash

RUN source $NVM_DIR/nvm.sh \
	&& nvm install $NODE_VERSION

ENV PATH $NVM_DIR/versions/node/$NODE_VERSION/bin:$PATH

CMD [ "/bin/bash" ]