FROM node:18

WORKDIR /data/donategifts

COPY package*.json .

RUN npm ci --ignore-scripts

COPY . .

RUN npm run build

RUN npm ci --omit=dev --ignore-scripts

EXPOSE 8080

ENTRYPOINT [ "npm", "start" ]