# fly.toml app configuration file generated for donate-gifts-test on 2023-07-07T20:53:51+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "donate-gifts-test"
primary_region = "ord"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
