const bcrypt = require('bcrypt');

const users = [
  {
    fName: 'John',
    lName: 'Doe',
    email: 'johndoe1@gmail.com',
    emailVerified: true,
    verificationHash: 'randomString1',
    userRole: 'Donor',
    password: bcrypt.hashSync('johndoe1!', 10),
    joined: Date.now(),
    aboutMe: 'A person passion to help kids of all ages.',
    loginMode: 'default',
  },
  {
    fName: 'John',
    lName: 'Doe',
    email: 'johndoe2@gmail.com',
    emailVerified: true,
    verificationHash: 'randomString2',
    userRole: 'partner',
    password: bcrypt.hashSync('johndoe2!', 10),
    joined: Date.now(),
    aboutMe: 'A person passion to help kids of all ages.',
    loginMode: 'default',
  },
  {
    fName: 'John',
    lName: 'Doe',
    email: 'johndoe3@gmail.com',
    emailVerified: true,
    verificationHash: 'randomString3',
    userRole: 'admin',
    password: bcrypt.hashSync('johndoe3!', 10),
    joined: Date.now(),
    aboutMe: 'A person passion to help kids of all ages.',
    loginMode: 'default',
  },
  {
    fName: 'John',
    lName: 'Doe',
    email: 'johndoe4@gmail.com',
    emailVerified: true,
    verificationHash: 'randomString4',
    userRole: 'Donor',
    password: bcrypt.hashSync('johndoe4!', 10),
    joined: Date.now(),
    aboutMe: 'A person passion to help kids of all ages.',
    loginMode: 'default',
  },
  {
    fName: 'John',
    lName: 'Doe',
    email: 'johndoe5@gmail.com',
    emailVerified: true,
    verificationHash: 'randomString5',
    userRole: 'partner',
    password: bcrypt.hashSync('johndoe5!', 10),
    joined: Date.now(),
    aboutMe: 'A person passion to help kids of all ages.',
    loginMode: 'default',
  },
  {
    fName: 'John',
    lName: 'Doe',
    email: 'johndoe6@gmail.com',
    emailVerified: true,
    verificationHash: 'randomString6',
    userRole: 'admin',
    password: bcrypt.hashSync('johndoe6!', 10),
    joined: Date.now(),
    aboutMe: 'A person passion to help kids of all ages.',
    loginMode: 'default',
  },
  {
    fName: 'John',
    lName: 'Doe',
    email: 'johndoe7@gmail.com',
    emailVerified: true,
    verificationHash: 'randomString7',
    userRole: 'Donor',
    password: bcrypt.hashSync('johndoe7!', 10),
    joined: Date.now(),
    aboutMe: 'A person passion to help kids of all ages.',
    loginMode: 'default',
  },
  {
    fName: 'John',
    lName: 'Doe',
    email: 'johndoe8@gmail.com',
    emailVerified: true,
    verificationHash: 'randomString8',
    userRole: 'partner',
    password: bcrypt.hashSync('johndoe8!', 10),
    joined: Date.now(),
    aboutMe: 'A person passion to help kids of all ages.',
    loginMode: 'default',
  },
  {
    fName: 'John',
    lName: 'Doe',
    email: 'johndoe9@gmail.com',
    emailVerified: true,
    verificationHash: 'randomString9',
    userRole: 'admin',
    password: bcrypt.hashSync('johndoe9!', 10),
    joined: Date.now(),
    aboutMe: 'A person passion to help kids of all ages.',
    loginMode: 'default',
  },
  {
    fName: 'John',
    lName: 'Doe',
    email: 'johndoe10@gmail.com',
    emailVerified: true,
    verificationHash: 'randomString10',
    userRole: 'Donor',
    password: bcrypt.hashSync('johndoe10!', 10),
    joined: Date.now(),
    aboutMe: 'A person passion to help kids of all ages.',
    loginMode: 'default',
  },
  {
    fName: 'Jane',
    lName: 'Doe',
    email: 'janedoe1@gmail.com',
    emailVerified: true,
    verificationHash: 'newRandomString1',
    userRole: 'partner',
    password: bcrypt.hashSync('janedoe1!', 10),
    joined: Date.now(),
    aboutMe: 'A person passion to help kids of all ages.',
    loginMode: 'default',
  },
  {
    fName: 'Jane',
    lName: 'Doe',
    email: 'janedoe2@gmail.com',
    emailVerified: true,
    verificationHash: 'newRandomString2',
    userRole: 'partner',
    password: bcrypt.hashSync('janedoe2!', 10),
    joined: Date.now(),
    aboutMe: 'A person passion to help kids of all ages.',
    loginMode: 'default',
  },
  {
    fName: 'Jane',
    lName: 'Doe',
    email: 'janedoe3@gmail.com',
    emailVerified: true,
    verificationHash: 'newRandomString3',
    userRole: 'partner',
    password: bcrypt.hashSync('janedoe3!', 10),
    joined: Date.now(),
    aboutMe: 'A person passion to help kids of all ages.',
    loginMode: 'default',
  },
  {
    fName: 'Jane',
    lName: 'Doe',
    email: 'janedoe4@gmail.com',
    emailVerified: true,
    verificationHash: 'newRandomString4',
    userRole: 'partner',
    password: bcrypt.hashSync('janedoe4!', 10),
    joined: Date.now(),
    aboutMe: 'A person passion to help kids of all ages.',
    loginMode: 'default',
  },
  {
    fName: 'Jane',
    lName: 'Doe',
    email: 'janedoe5@gmail.com',
    emailVerified: true,
    verificationHash: 'newRandomString5',
    userRole: 'partner',
    password: bcrypt.hashSync('janedoe5!', 10),
    joined: Date.now(),
    aboutMe: 'A person passion to help kids of all ages.',
    loginMode: 'default',
  },
  {
    fName: 'Jane',
    lName: 'Doe',
    email: 'janedoe6@gmail.com',
    emailVerified: true,
    verificationHash: 'newRandomString6',
    userRole: 'partner',
    password: bcrypt.hashSync('janedoe6!', 10),
    joined: Date.now(),
    aboutMe: 'A person passion to help kids of all ages.',
    loginMode: 'default',
  },
  {
    fName: 'Jane',
    lName: 'Doe',
    email: 'janedoe7@gmail.com',
    emailVerified: true,
    verificationHash: 'newRandomString7',
    userRole: 'partner',
    password: bcrypt.hashSync('janedoe7!', 10),
    joined: Date.now(),
    aboutMe: 'A person passion to help kids of all ages.',
    loginMode: 'default',
  },
  {
    fName: 'Jane',
    lName: 'Doe',
    email: 'janedoe8@gmail.com',
    emailVerified: true,
    verificationHash: 'newRandomString8',
    userRole: 'partner',
    password: bcrypt.hashSync('janedoe8!', 10),
    joined: Date.now(),
    aboutMe: 'A person passion to help kids of all ages.',
    loginMode: 'default',
  },
  {
    fName: 'Jane',
    lName: 'Doe',
    email: 'janedoe9@gmail.com',
    emailVerified: true,
    verificationHash: 'newRandomString9',
    userRole: 'partner',
    password: bcrypt.hashSync('janedoe9!', 10),
    joined: Date.now(),
    aboutMe: 'A person passion to help kids of all ages.',
    loginMode: 'default',
  },
  {
    fName: 'Jane',
    lName: 'Doe',
    email: 'janedoe10@gmail.com',
    emailVerified: true,
    verificationHash: 'newRandomString10',
    userRole: 'partner',
    password: bcrypt.hashSync('janedoe10!', 10),
    joined: Date.now(),
    aboutMe: 'A person passion to help kids of all ages.',
    loginMode: 'default',
  },
];

const wishcards = [
  {
    approvedByAdmin: true,
    childFirstName: 'princess',
    childLastName: 'Elsa',
    childInterest: 'playing video games',
    wishItemName: 'Amazon Gift Card LOL',
    wishCardImage: 'https://source.unsplash.com/random/400x400',
    wishItemURL: 'https://www.google.com',
    wishItemPrice: '40',
    childStory: 'Kid that needs a gift for the holidays',
    deliveryDate: Date.now(),
    occasion: 'Some Occasion',
    address: {
      address1: '1337 leet road',
      city: 'Magic Kingdom',
      state: 'Florida',
      country: 'Merica',
      zipcode: '78452',
    },
    isDonated: false,
    status: 'draft',
  },
  {
    approvedByAdmin: true,
    childFirstName: 'princess',
    childLastName: 'Stacey',
    childInterest: 'playing video games',
    wishItemName: 'Amazon Gift Card LOL',
    wishCardImage: 'https://source.unsplash.com/random/400x400',
    wishItemURL: 'https://www.google.com',
    wishItemPrice: '40',
    childStory: 'Kid that needs a gift for the holidays',
    deliveryDate: Date.now(),
    occasion: 'Some Occasion',
    address: {
      address1: '1337 leet road',
      city: 'Magic Kingdom',
      state: 'Florida',
      country: 'Merica',
      zipcode: '78452',
    },
    isDonated: false,
    status: 'published',
  },
  {
    approvedByAdmin: true,
    childFirstName: 'not_donated',
    childLastName: 'patric',
    childInterest: 'playing video games',
    wishItemName: 'Amazon Gift Card LOL',
    wishCardImage: 'https://source.unsplash.com/random/400x400',
    wishItemURL: 'https://www.amazon.com/gp/item-dispatch?registryID.1=25G0Z099HL6MM&registryItemID.1=I1O9RO1YPYHIAY&offeringID.1=MQVghiAmdPee43XLIJC7O6kWUui9P98LhUCjO0h40whWzMUZCD7cEt0fKU%252BHR1EGx%252Fo28ERQSrDbhtckSAslzk0c97WwWaXJiWXNjy6X3Aidfe6cpu1OR6K9KNs1s6Jmlk8DBvPUg%252F2HZgxckwFTQipnJfDHLce%252FjNpFnk7FGJRbuiw2d0DE7w%253D%253D&session-id=146-5423461-6179443&isGift=0&submit.addToCart=1&quantity.1=1&ref_=lv_ov_lig_pab',
    wishItemPrice: '40',
    childStory: 'Kid that needs a gift for the holidays',
    deliveryDate: Date.now(),
    occasion: 'Some Occasion',
    address: {
      address1: '1337 leet road',
      city: 'Magic Kingdom',
      state: 'Florida',
      country: 'Merica',
      zipcode: '78452',
    },
    isDonated: false,
    status: 'donated',
  },
  {
    approvedByAdmin: true,
    childFirstName: 'donated',
    childLastName: 'Marco',
    childInterest: 'playing video games',
    wishItemName: 'Amazon Gift Card LOL',
    wishCardImage: 'https://source.unsplash.com/random/400x400',
    wishItemURL: 'https://www.amazon.com/gp/item-dispatch?registryID.1=1G59GOMP7TWWL&registryItemID.1=I2GEAHF4IG70OQ&offeringID.1=KOpMfeBdDkwVCEdd3iLwzcg%252BuAvNV1yFQZ4WZd6zANLbt0Yru%252B8qTa1ZhDPOyCGOMjrUHXJWyEhpF6T5xvKmzUSfD5YbyHRIT3bHBPKYK6zijeQf31xLEVIi8D0bM8qiBozSqXn%252FXQh7U0AoYxlwiA8TbpZUxoXtnEcPKkZucW4UvD8SlLCakLpkDlzhG02X&session-id=146-5423461-6179443&isGift=0&submit.addToCart=1&quantity.1=1&ref_=lv_ov_lig_pab',
    wishItemPrice: '40',
    childStory: 'Kid that needs a gift for the holidays',
    deliveryDate: Date.now(),
    occasion: 'Some Occasion',
    address: {
      address1: '1337 leet road',
      city: 'Magic Kingdom',
      state: 'Florida',
      country: 'Merica',
      zipcode: '78452',
    },
    isDonated: false,
    status: 'draft',
  },
  {
    approvedByAdmin: true,
    childFirstName: 'princess',
    childLastName: 'Tokkiko',
    childInterest: 'playing video games',
    wishItemName: 'Amazon Gift Card LOL',
    wishCardImage: 'https://source.unsplash.com/random/400x400',
    wishItemURL: 'https://www.google.com',
    wishItemPrice: '40',
    childStory: 'Kid that needs a gift for the holidays',
    deliveryDate: Date.now(),
    occasion: 'Some Occasion',
    address: {
      address1: '1337 leet road',
      city: 'Magic Kingdom',
      state: 'Florida',
      country: 'Merica',
      zipcode: '78452',
    },
    isDonated: false,
    status: 'published',
  },
  {
    approvedByAdmin: true,
    childFirstName: 'princess',
    childLastName: 'Markell',
    childInterest: 'playing video games',
    wishItemName: 'Amazon Gift Card LOL',
    wishCardImage: 'https://source.unsplash.com/random/400x400',
    wishItemURL: 'https://www.google.com',
    wishItemPrice: '40',
    childStory: 'Kid that needs a gift for the holidays',
    deliveryDate: Date.now(),
    occasion: 'Some Occasion',
    address: {
      address1: '1337 leet road',
      city: 'Magic Kingdom',
      state: 'Florida',
      country: 'Merica',
      zipcode: '78452',
    },
    isDonated: false,
    status: 'donated',
  },
  {
    approvedByAdmin: true,
    childFirstName: 'princess',
    childLastName: 'Deep',
    childInterest: 'playing video games',
    wishItemName: 'Amazon Gift Card LOL',
    wishCardImage: 'https://source.unsplash.com/random/400x400',
    wishItemURL: 'https://www.google.com',
    wishItemPrice: '40',
    childStory: 'Kid that needs a gift for the holidays',
    deliveryDate: Date.now(),
    occasion: 'Some Occasion',
    address: {
      address1: '1337 leet road',
      city: 'Magic Kingdom',
      state: 'Florida',
      country: 'Merica',
      zipcode: '78452',
    },
    isDonated: false,
    status: 'draft',
  },
  {
    approvedByAdmin: true,
    childFirstName: 'princess',
    childLastName: 'Fillip',
    childInterest: 'playing video games',
    wishItemName: 'Amazon Gift Card LOL',
    wishCardImage: 'https://source.unsplash.com/random/400x400',
    wishItemURL: 'https://www.google.com',
    wishItemPrice: '40',
    childStory: 'Kid that needs a gift for the holidays',
    deliveryDate: Date.now(),
    occasion: 'Some Occasion',
    address: {
      address1: '1337 leet road',
      city: 'Magic Kingdom',
      state: 'Florida',
      country: 'Merica',
      zipcode: '78452',
    },
    isDonated: false,
    status: 'published',
  },
  {
    approvedByAdmin: true,
    childFirstName: 'princess',
    childLastName: 'Maria',
    childInterest: 'playing video games',
    wishItemName: 'Amazon Gift Card LOL',
    wishCardImage: 'https://source.unsplash.com/random/400x400',
    wishItemURL: 'https://www.google.com',
    wishItemPrice: '40',
    childStory: 'Kid that needs a gift for the holidays',
    deliveryDate: Date.now(),
    occasion: 'Some Occasion',
    address: {
      address1: '1337 leet road',
      city: 'Magic Kingdom',
      state: 'Florida',
      country: 'Merica',
      zipcode: '78452',
    },
    isDonated: false,
    status: 'donated',
  },
  {
    approvedByAdmin: true,
    childFirstName: 'princess',
    childLastName: 'Karen',
    childInterest: 'playing video games',
    wishItemName: 'Amazon Gift Card LOL',
    wishCardImage: 'https://source.unsplash.com/random/400x400',
    wishItemURL: 'https://www.google.com',
    wishItemPrice: '40',
    childStory: 'Kid that needs a gift for the holidays',
    deliveryDate: Date.now(),
    occasion: 'Some Occasion',
    address: {
      address1: '1337 leet road',
      city: 'Magic Kingdom',
      state: 'Florida',
      country: 'Merica',
      zipcode: '78452',
    },
    isDonated: false,
    status: 'draft',
  },
  {
    approvedByAdmin: true,
    childFirstName: 'princess',
    childLastName: 'Bubba',
    childInterest: 'playing video games',
    wishItemName: 'Amazon Gift Card LOL',
    wishCardImage: 'https://source.unsplash.com/random/400x400',
    wishItemURL: 'https://www.google.com',
    wishItemPrice: '40',
    childStory: 'Kid that needs a gift for the holidays',
    deliveryDate: Date.now(),
    occasion: 'Some Occasion',
    address: {
      address1: '1337 leet road',
      city: 'Magic Kingdom',
      state: 'Florida',
      country: 'Merica',
      zipcode: '78452',
    },
    isDonated: false,
    status: 'published',
  },
  {
    approvedByAdmin: true,
    childFirstName: 'princess',
    childLastName: 'Gut',
    childInterest: 'playing video games',
    wishItemName: 'Amazon Gift Card LOL',
    wishCardImage: 'https://source.unsplash.com/random/400x400',
    wishItemURL: 'https://www.google.com',
    wishItemPrice: '40',
    childStory: 'Kid that needs a gift for the holidays',
    deliveryDate: Date.now(),
    occasion: 'Some Occasion',
    address: {
      address1: '1337 leet road',
      city: 'Magic Kingdom',
      state: 'Florida',
      country: 'Merica',
      zipcode: '78452',
    },
    isDonated: false,
    status: 'donated',
  },
];

const agency = {
  agencyName: 'SaveDaKids',
  agencyWebsite: 'savedakids.com',
  agencyPhone: '281-330-8004',
  agencyBio: 'Comitted to saving the kids!',
  agencyAddress: {
    address1: '911 cops road',
    address2: '311 Amber Dr',
    city: 'Epcot',
    state: 'Florida',
    country: 'Merica',
    zipcode: '78452',
  },
  childrenUnderCare: 15,
  childrenAgeRange: '1-18',
  joined: Date.now(),
  isVerified: true,
  agencyProfileImage: 'https://source.unsplash.com/random/400x400',
};
module.exports = { users, wishcards, agency };
