FROM node:16

COPY /package.json /app
COPY /dist /app

WORKDIR /app

RUN npm ci --only=production

ENV NODE_ENV=${NODE_ENV}
ENV MYSQL_USER=${MYSQL_USER},
ENV MYSQL_PASSWORD=${MYSQL_PASSWORD},
ENV MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD},
ENV MYSQL_DATABASE=${MYSQL_DATABASE},
ENV MYSQL_URL=${MYSQL_URL},
ENV SHADOW_DATABASE_URL=${SHADOW_DATABASE_URL},
ENV JWT_SECRET=${JWT_SECRET},
ENV JWT_TOKEN_EXPIRES_IN=${JWT_TOKEN_EXPIRES_IN},
ENV JWT_REFRESH_TOKEN_EXPIRES_IN=${JWT_REFRESH_TOKEN_EXPIRES_IN},

RUN npm start
