const LOGIN = 'LOGIN';
const LOGIN_WITH_EMAIL = 'LOGIN_WITH_EMAIL';
const SIGNUP = 'SIGNUP';

const GOOGLE_CLIENT_LIBRARY_URL = 'https://accounts.google.com/gsi/client';

const STATE_NAMES = [
	'Alabama',
	'Alaska',
	'Arizona',
	'Arkansas',
	'California',
	'Colorado',
	'Connecticut',
	'Delaware',
	'Florida',
	'Georgia',
	'Hawaii',
	'Idaho',
	'Illinois',
	'Indiana',
	'Iowa',
	'Kansas',
	'Kentucky',
	'Louisiana',
	'Maine',
	'Maryland',
	'Massachusetts',
	'Michigan',
	'Minnesota',
	'Mississippi',
	'Missouri',
	'Montana',
	'Nebraska',
	'Nevada',
	'New Hampshire',
	'New Jersey',
	'New Mexico',
	'New York',
	'North Carolina',
	'North Dakota',
	'Ohio',
	'Oklahoma',
	'Oregon',
	'Pennsylvania',
	'Rhode Island',
	'South Carolina',
	'South Dakota',
	'Tennessee',
	'Texas',
	'Utah',
	'Vermont',
	'Virginia',
	'Washington',
	'West Virginia',
	'Wisconsin',
	'Wyoming',
];

export { LOGIN, LOGIN_WITH_EMAIL, SIGNUP, GOOGLE_CLIENT_LIBRARY_URL, STATE_NAMES };
