const bcrypt = require('bcrypt');

const users = [
  {
    fName: 'John',
    lName: 'Doe',
<<<<<<< HEAD
    email: 'johndoe1@gmail.com',
    emailVerified: true,
    verificationHash: 'randomString1',
    userRole: 'Donor',
    password: bcrypt.hashSync('johndoe1!', 10),
    joined: Date.now(),
    aboutMe: 'A person passion to help kids of all ages.',
    loginMode: 'default',
  },
  {
    fName: 'John',
    lName: 'Doe',
    email: 'johndoe2@gmail.com',
    emailVerified: true,
    verificationHash: 'randomString2',
    userRole: 'partner',
    password: bcrypt.hashSync('johndoe2!', 10),
    joined: Date.now(),
    aboutMe: 'A person passion to help kids of all ages.',
    loginMode: 'default',
  },
  {
    fName: 'John',
    lName: 'Doe',
    email: 'johndoe3@gmail.com',
    emailVerified: true,
    verificationHash: 'randomString3',
    userRole: 'admin',
    password: bcrypt.hashSync('johndoe3!', 10),
    joined: Date.now(),
    aboutMe: 'A person passion to help kids of all ages.',
    loginMode: 'default',
  },
  {
    fName: 'John',
    lName: 'Doe',
    email: 'johndoe4@gmail.com',
    emailVerified: true,
    verificationHash: 'randomString4',
    userRole: 'Donor',
    password: bcrypt.hashSync('johndoe4!', 10),
    joined: Date.now(),
    aboutMe: 'A person passion to help kids of all ages.',
    loginMode: 'default',
  },
  {
    fName: 'John',
    lName: 'Doe',
    email: 'johndoe5@gmail.com',
    emailVerified: true,
    verificationHash: 'randomString5',
    userRole: 'partner',
    password: bcrypt.hashSync('johndoe5!', 10),
    joined: Date.now(),
    aboutMe: 'A person passion to help kids of all ages.',
    loginMode: 'default',
  },
  {
    fName: 'John',
    lName: 'Doe',
    email: 'johndoe6@gmail.com',
    emailVerified: true,
    verificationHash: 'randomString6',
    userRole: 'admin',
    password: bcrypt.hashSync('johndoe6!', 10),
    joined: Date.now(),
    aboutMe: 'A person passion to help kids of all ages.',
    loginMode: 'default',
  },
  {
    fName: 'John',
    lName: 'Doe',
    email: 'johndoe7@gmail.com',
    emailVerified: true,
    verificationHash: 'randomString7',
    userRole: 'Donor',
    password: bcrypt.hashSync('johndoe7!', 10),
    joined: Date.now(),
    aboutMe: 'A person passion to help kids of all ages.',
    loginMode: 'default',
  },
  {
    fName: 'John',
    lName: 'Doe',
    email: 'johndoe8@gmail.com',
    emailVerified: true,
    verificationHash: 'randomString8',
    userRole: 'partner',
    password: bcrypt.hashSync('johndoe8!', 10),
    joined: Date.now(),
    aboutMe: 'A person passion to help kids of all ages.',
    loginMode: 'default',
  },
  {
    fName: 'John',
    lName: 'Doe',
    email: 'johndoe9@gmail.com',
    emailVerified: true,
    verificationHash: 'randomString9',
    userRole: 'admin',
    password: bcrypt.hashSync('johndoe9!', 10),
    joined: Date.now(),
    aboutMe: 'A person passion to help kids of all ages.',
    loginMode: 'default',
  },
  {
    fName: 'John',
    lName: 'Doe',
    email: 'johndoe10@gmail.com',
    emailVerified: true,
    verificationHash: 'randomString10',
    userRole: 'Donor',
    password: bcrypt.hashSync('johndoe10!', 10),
    joined: Date.now(),
    aboutMe: 'A person passion to help kids of all ages.',
    loginMode: 'default',
=======
    email: 'johndoe@gmail.com',
    emailVerified: true,
    verificationHash: 'randomString',
    userRole: 'Donor',
    password: bcrypt.hashSync('johndoe1!', 10),
>>>>>>> master
  },
  {
    fName: 'Jane',
    lName: 'Doe',
<<<<<<< HEAD
    email: 'janedoe1@gmail.com',
    emailVerified: true,
    verificationHash: 'newRandomString1',
    userRole: 'partner',
    password: bcrypt.hashSync('janedoe1!', 10),
    joined: Date.now(),
    aboutMe: 'A person passion to help kids of all ages.',
    loginMode: 'default',
  },
  {
    fName: 'Jane',
    lName: 'Doe',
    email: 'janedoe2@gmail.com',
    emailVerified: true,
    verificationHash: 'newRandomString2',
    userRole: 'partner',
    password: bcrypt.hashSync('janedoe2!', 10),
    joined: Date.now(),
    aboutMe: 'A person passion to help kids of all ages.',
    loginMode: 'default',
  },
  {
    fName: 'Jane',
    lName: 'Doe',
    email: 'janedoe3@gmail.com',
    emailVerified: true,
    verificationHash: 'newRandomString3',
    userRole: 'partner',
    password: bcrypt.hashSync('janedoe3!', 10),
    joined: Date.now(),
    aboutMe: 'A person passion to help kids of all ages.',
    loginMode: 'default',
  },
  {
    fName: 'Jane',
    lName: 'Doe',
    email: 'janedoe4@gmail.com',
    emailVerified: true,
    verificationHash: 'newRandomString4',
    userRole: 'partner',
    password: bcrypt.hashSync('janedoe4!', 10),
    joined: Date.now(),
    aboutMe: 'A person passion to help kids of all ages.',
    loginMode: 'default',
  },
  {
    fName: 'Jane',
    lName: 'Doe',
    email: 'janedoe5@gmail.com',
    emailVerified: true,
    verificationHash: 'newRandomString5',
    userRole: 'partner',
    password: bcrypt.hashSync('janedoe5!', 10),
    joined: Date.now(),
    aboutMe: 'A person passion to help kids of all ages.',
    loginMode: 'default',
  },
  {
    fName: 'Jane',
    lName: 'Doe',
    email: 'janedoe6@gmail.com',
    emailVerified: true,
    verificationHash: 'newRandomString6',
    userRole: 'partner',
    password: bcrypt.hashSync('janedoe6!', 10),
    joined: Date.now(),
    aboutMe: 'A person passion to help kids of all ages.',
    loginMode: 'default',
  },
  {
    fName: 'Jane',
    lName: 'Doe',
    email: 'janedoe7@gmail.com',
    emailVerified: true,
    verificationHash: 'newRandomString7',
    userRole: 'partner',
    password: bcrypt.hashSync('janedoe7!', 10),
    joined: Date.now(),
    aboutMe: 'A person passion to help kids of all ages.',
    loginMode: 'default',
  },
  {
    fName: 'Jane',
    lName: 'Doe',
    email: 'janedoe8@gmail.com',
    emailVerified: true,
    verificationHash: 'newRandomString8',
    userRole: 'partner',
    password: bcrypt.hashSync('janedoe8!', 10),
    joined: Date.now(),
    aboutMe: 'A person passion to help kids of all ages.',
    loginMode: 'default',
  },
  {
    fName: 'Jane',
    lName: 'Doe',
    email: 'janedoe9@gmail.com',
    emailVerified: true,
    verificationHash: 'newRandomString9',
    userRole: 'partner',
    password: bcrypt.hashSync('janedoe9!', 10),
    joined: Date.now(),
    aboutMe: 'A person passion to help kids of all ages.',
    loginMode: 'default',
  },
  {
    fName: 'Jane',
    lName: 'Doe',
    email: 'janedoe10@gmail.com',
    emailVerified: true,
    verificationHash: 'newRandomString10',
    userRole: 'partner',
    password: bcrypt.hashSync('janedoe10!', 10),
    joined: Date.now(),
    aboutMe: 'A person passion to help kids of all ages.',
    loginMode: 'default',
=======
    email: 'janedoe@gmail.com',
    emailVerified: true,
    verificationHash: 'anotherRandomString',
    password: bcrypt.hashSync('janedoe1!', 10),
    userRole: 'Partner',
  },
  {
    fName: 'Ricky',
    lName: 'bobby',
    email: 'rickybobby@gmail.com',
    emailVerified: true,
    verificationHash: 'oogabooga',
    password: bcrypt.hashSync('rickybobby1!', 10),
    userRole: 'admin',
>>>>>>> master
  },
];

const wishcards = [
  {
<<<<<<< HEAD
    approvedByAdmin: true,
    childFirstName: 'princess',
    childLastName: 'Elsa',
    childInterest: 'playing video games',
    wishItemName: 'Amazon Gift Card LOL',
    wishCardImage: 'https://source.unsplash.com/random/400x400',
    wishItemURL: 'https://www.google.com',
    wishItemPrice: '40',
    childStory: 'Kid that needs a gift for the holidays',
    deliveryDate: Date.now(),
    occasion: 'Some Occasion',
    address: {
      address1: '1337 leet road',
      city: 'Magic Kingdom',
      state: 'Florida',
      country: 'Merica',
      zipcode: '78452',
    },
    isDonated: false,
    status: 'draft',
  },
  {
    approvedByAdmin: true,
    childFirstName: 'princess',
    childLastName: 'Stacey',
    childInterest: 'playing video games',
    wishItemName: 'Amazon Gift Card LOL',
    wishCardImage: 'https://source.unsplash.com/random/400x400',
    wishItemURL: 'https://www.google.com',
    wishItemPrice: '40',
    childStory: 'Kid that needs a gift for the holidays',
    deliveryDate: Date.now(),
    occasion: 'Some Occasion',
    address: {
      address1: '1337 leet road',
      city: 'Magic Kingdom',
      state: 'Florida',
      country: 'Merica',
      zipcode: '78452',
    },
    isDonated: false,
    status: 'published',
  },
  {
    approvedByAdmin: true,
    childFirstName: 'princess',
    childLastName: 'patric',
    childInterest: 'playing video games',
    wishItemName: 'Amazon Gift Card LOL',
    wishCardImage: 'https://source.unsplash.com/random/400x400',
    wishItemURL: 'https://www.google.com',
    wishItemPrice: '40',
    childStory: 'Kid that needs a gift for the holidays',
    deliveryDate: Date.now(),
    occasion: 'Some Occasion',
    address: {
      address1: '1337 leet road',
      city: 'Magic Kingdom',
      state: 'Florida',
      country: 'Merica',
      zipcode: '78452',
    },
    isDonated: false,
    status: 'donated',
  },
  {
    approvedByAdmin: true,
    childFirstName: 'princess',
    childLastName: 'Marco',
    childInterest: 'playing video games',
    wishItemName: 'Amazon Gift Card LOL',
    wishCardImage: 'https://source.unsplash.com/random/400x400',
    wishItemURL: 'https://www.google.com',
    wishItemPrice: '40',
    childStory: 'Kid that needs a gift for the holidays',
    deliveryDate: Date.now(),
    occasion: 'Some Occasion',
    address: {
      address1: '1337 leet road',
      city: 'Magic Kingdom',
      state: 'Florida',
      country: 'Merica',
      zipcode: '78452',
    },
    isDonated: false,
    status: 'draft',
  },
  {
    approvedByAdmin: true,
    childFirstName: 'princess',
    childLastName: 'Tokkiko',
    childInterest: 'playing video games',
    wishItemName: 'Amazon Gift Card LOL',
    wishCardImage: 'https://source.unsplash.com/random/400x400',
    wishItemURL: 'https://www.google.com',
    wishItemPrice: '40',
    childStory: 'Kid that needs a gift for the holidays',
    deliveryDate: Date.now(),
    occasion: 'Some Occasion',
    address: {
      address1: '1337 leet road',
      city: 'Magic Kingdom',
      state: 'Florida',
      country: 'Merica',
      zipcode: '78452',
    },
    isDonated: false,
    status: 'published',
  },
  {
    approvedByAdmin: true,
    childFirstName: 'princess',
    childLastName: 'Markell',
    childInterest: 'playing video games',
    wishItemName: 'Amazon Gift Card LOL',
    wishCardImage: 'https://source.unsplash.com/random/400x400',
    wishItemURL: 'https://www.google.com',
    wishItemPrice: '40',
    childStory: 'Kid that needs a gift for the holidays',
    deliveryDate: Date.now(),
    occasion: 'Some Occasion',
    address: {
      address1: '1337 leet road',
      city: 'Magic Kingdom',
      state: 'Florida',
      country: 'Merica',
      zipcode: '78452',
    },
    isDonated: false,
    status: 'donated',
  },
  {
    approvedByAdmin: true,
    childFirstName: 'princess',
    childLastName: 'Deep',
    childInterest: 'playing video games',
    wishItemName: 'Amazon Gift Card LOL',
    wishCardImage: 'https://source.unsplash.com/random/400x400',
    wishItemURL: 'https://www.google.com',
    wishItemPrice: '40',
    childStory: 'Kid that needs a gift for the holidays',
    deliveryDate: Date.now(),
    occasion: 'Some Occasion',
    address: {
      address1: '1337 leet road',
      city: 'Magic Kingdom',
      state: 'Florida',
      country: 'Merica',
      zipcode: '78452',
    },
    isDonated: false,
    status: 'draft',
  },
  {
    approvedByAdmin: true,
    childFirstName: 'princess',
    childLastName: 'Fillip',
    childInterest: 'playing video games',
    wishItemName: 'Amazon Gift Card LOL',
    wishCardImage: 'https://source.unsplash.com/random/400x400',
    wishItemURL: 'https://www.google.com',
    wishItemPrice: '40',
    childStory: 'Kid that needs a gift for the holidays',
    deliveryDate: Date.now(),
    occasion: 'Some Occasion',
    address: {
      address1: '1337 leet road',
      city: 'Magic Kingdom',
      state: 'Florida',
      country: 'Merica',
      zipcode: '78452',
    },
    isDonated: false,
    status: 'published',
  },
  {
    approvedByAdmin: true,
    childFirstName: 'princess',
    childLastName: 'Maria',
    childInterest: 'playing video games',
    wishItemName: 'Amazon Gift Card LOL',
    wishCardImage: 'https://source.unsplash.com/random/400x400',
    wishItemURL: 'https://www.google.com',
    wishItemPrice: '40',
    childStory: 'Kid that needs a gift for the holidays',
    deliveryDate: Date.now(),
    occasion: 'Some Occasion',
    address: {
      address1: '1337 leet road',
      city: 'Magic Kingdom',
      state: 'Florida',
      country: 'Merica',
      zipcode: '78452',
    },
    isDonated: false,
    status: 'donated',
  },
  {
    approvedByAdmin: true,
    childFirstName: 'princess',
    childLastName: 'Karen',
    childInterest: 'playing video games',
    wishItemName: 'Amazon Gift Card LOL',
    wishCardImage: 'https://source.unsplash.com/random/400x400',
    wishItemURL: 'https://www.google.com',
    wishItemPrice: '40',
    childStory: 'Kid that needs a gift for the holidays',
    deliveryDate: Date.now(),
    occasion: 'Some Occasion',
    address: {
      address1: '1337 leet road',
      city: 'Magic Kingdom',
      state: 'Florida',
      country: 'Merica',
      zipcode: '78452',
    },
    isDonated: false,
    status: 'draft',
  },
  {
    approvedByAdmin: true,
    childFirstName: 'princess',
    childLastName: 'Bubba',
    childInterest: 'playing video games',
    wishItemName: 'Amazon Gift Card LOL',
    wishCardImage: 'https://source.unsplash.com/random/400x400',
    wishItemURL: 'https://www.google.com',
    wishItemPrice: '40',
    childStory: 'Kid that needs a gift for the holidays',
    deliveryDate: Date.now(),
    occasion: 'Some Occasion',
    address: {
      address1: '1337 leet road',
      city: 'Magic Kingdom',
      state: 'Florida',
      country: 'Merica',
      zipcode: '78452',
    },
    isDonated: false,
    status: 'published',
  },
  {
    approvedByAdmin: true,
    childFirstName: 'princess',
    childLastName: 'Gut',
    childInterest: 'playing video games',
    wishItemName: 'Amazon Gift Card LOL',
    wishCardImage: 'https://source.unsplash.com/random/400x400',
    wishItemURL: 'https://www.google.com',
    wishItemPrice: '40',
    childStory: 'Kid that needs a gift for the holidays',
    deliveryDate: Date.now(),
    occasion: 'Some Occasion',
    address: {
      address1: '1337 leet road',
      city: 'Magic Kingdom',
      state: 'Florida',
      country: 'Merica',
      zipcode: '78452',
    },
    isDonated: false,
    status: 'donated',
  },
];

const agency = {
  agencyName: 'SaveDaKids',
  agencyWebsite: 'savedakids.com',
  agencyPhone: '281-330-8004',
  agencyBio: 'Comitted to saving the kids!',
  agencyAddress: {
    address1: '911 cops road',
    address2: '311 Amber Dr',
    city: 'Epcot',
    state: 'Florida',
    country: 'Merica',
    zipcode: '78452',
  },
  childrenUnderCare: 15,
  childrenAgeRange: '1-18',
  joined: Date.now(),
  isVerified: true,
  agencyProfileImage: 'https://source.unsplash.com/random/400x400',
};
module.exports = { users, wishcards, agency };
=======
    childFirstName: 'princess',
    chaldLastName: 'Elsa',
    wishItemName: 'Amazon Gift Card LOL',
    wishItemImage: 'https://picsum.photos/seed/picsum/300/300',
    wishItemUrl: 'https://www.google.com',
  },
  {
    childFirstName: 'princess',
    chaldLastName: 'Stacey',
    wishItemName: 'Amazon Gift Card LOL',
    wishItemImage: 'https://picsum.photos/seed/picsum/300/300',
    wishItemUrl: 'https://www.google.com',
  },
  {
    childFirstName: 'princess',
    chaldLastName: 'Patric',
    wishItemName: 'Amazon Gift Card LOL',
    wishItemImage: 'https://picsum.photos/seed/picsum/300/300',
    wishItemUrl: 'https://www.google.com',
  },
];

module.exports = { users, wishcards };
>>>>>>> master
