# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run build and test pipeline

on:
  pull_request:
    types:
      - assigned
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - v2

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]

    services:
      mysql:
        image: mariadb:latest
        env:
          MYSQL_USER: mysql
          MYSQL_PASSWORD: mysql
          MYSQL_DATABASE: donategifts
          MYSQL_ROOT_PASSWORD: mysqlroot
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Verify MariaDB connection
        env:
          PORT: 3306
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install modules
        run: npm install

      - name: Eslint
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Test
        run: npm run coverage-ci

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
